Alvarez dev1 78/comentarios eliminacion console log formateo vareables
lautaroncoria/proyecto-valtech-academy pull request #6
Opened 2022-10-21 18:45 UTC by GonzaloAlvrz

Se agrego las peticiones

2022-10-24 13:16 UTC, SofiaSerrano2 commented on front/src/pages/PrivatePages/sharedPrivateComponents/menu/MenuResponsive.jsx
>      }
Esta función debería ser eliminada porque ya no existe la función(al menos por parte de back) para salir, porque desde nuestro lado para que ya no se puedan hacer peticiones solo dejamos de mandar el token.

2022-10-24 13:22 UTC, SofiaSerrano2 commented on front/src/pages/PrivatePages/AssignCounselor/AssignCounselorPage.jsx
La petición de getAlladviser y asignAdiver deberían hacerse llamando a los customsHooks como useGet y usePost.

2022-10-24 13:29 UTC, GonzaloAlvrz commented on front/src/pages/PrivatePages/AssignCounselor/AssignCounselorPage.jsx
>                        <h4 className='text-[15px] leading-[22px]  ml-6 text-lightgray'>Orientador</h4>
Dale Sofi, ahora empiezo con los cambios. Gracias.

2022-10-24 14:00 UTC, lautaroncoria reviewed
Gonza, son algunas sugerencias, seguramente se me escaparon cosas. Avisame si necesitás una mano o cualquier duda y lo vemos! 💪

2022-10-24 14:00 UTC, lautaroncoria commented on front/src/pages/PrivatePages/sharedPrivateComponents/menu/MenuComponent.jsx
> +            <svg
Estas imágenes no te conviene importarlas mejor? Guardarlas en la carpeta assets e importarlas luego? Así achicamos el código

2022-10-24 14:17 UTC, SofiaSerrano2 commented on front/src/pages/PrivatePages/sharedPrivateComponents/menu/MenuResponsive.jsx
>    };
Hay que cambia el nombre de la constante deslogearme a `logOut` porque también le cambie el nombre en el context

2022-10-24 14:19 UTC, SofiaSerrano2 commented on front/src/pages/PrivatePages/sharedPrivateComponents/menu/MenuResponsive.jsx
>    const { deslogearme } = useContext(Context);
Tendría que estar así ahora 
```suggestion
  const { logOut} = useContext(Context);
```

2022-10-25 15:01 UTC, Mauro-Accorinti requested changes

2022-10-25 20:23 UTC, merged